name: Mobsfscanning Mobile App
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set-up Java
        uses: actions/setup-java@v1
        with:
          java-version: '12.x'

      - name: Set-up Flutter
        uses: subosito/flutter-action@v2

      - name: Flutter Install Dependencies
        run: flutter pub get

      # - name: Flutter Test
      #   run: flutter test

      - name: Flutter Build
        run: flutter build apk

      # - name: Run MobSF Analysis
      #   uses: fundacaocerti/mobsf-action@v1.7.1
      #   env:
      #     INPUT_FILE_NAME: build/app/outputs/apk/release/app-release.apk
      #     SCAN_TYPE: apk
      #     OUTPUT_FILE_NAME: mobsf-report

      # - name: Upload MobSF Analysis PDF Result
      #   uses: actions/upload-artifact@v2
        # with:
        #   name: mobsf-report.pdf
        #   path: mobsf-report.pdf

      # - name: Upload MobSF Analysis JSON Result
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: mobsf-report.json
      #     path: mobsf-report.json

      - name: Run MobSF Analysis
        uses: MobSF/mobsfscan@main
        with:
          args: 'path "build/app/outputs/apk/release/app-release.apk" --sarif --output results.sarif  --json --output results.json || true'


      - name: Upload MobSF Analysis PDF Result
        uses: actions/upload-artifact@v2
        with:
          name: results.json
          path: results.json
        
        # with:
        #   args: 'path "build/app/outputs/apk/release/app-release.apk" --sarif --output results.sarif || true'

      - name: Upload mobsfscan report
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: results.sarif